version: '3.9'
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver_hotel
        ports:
            - '1433:1433'
        environment:
            ACCEPT_EULA: 'Y'
            SA_PASSWORD: 'SApassword@123'
            MSSQL_PID: 'Developer'
            MSSQL_DISABLE_TLS: 'true'
        volumes:
            - ./mssql:/scripts
        restart: unless-stopped
